// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id:
    'us-east-1:1f309c8c-10ea-4f8d-99c5-deb82e94696e',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_dKxxMytBU',
  aws_user_pools_web_client_id: '1ervntt9bmbl89b7f5d5c1h1ct',
  oauth: {},
  aws_appsync_graphqlEndpoint:
    'https://zwibm7wctvggrapdhtf5kkd77i.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
};

export default awsmobile;
